### PR TITLE
Fix for the window sub-menu mnemonics

### PR DESCRIPTION
**Pull request by punker76**
This PR will fix the [SO](https://stackoverflow.com/questions/50431171/wpf-how-to-get-dynamically-added-menu-item-mnemonics-to-work) question and issue.

The sub menus of the window menu shows their mnemonics but it will not execute the commands behind. This is happen caused by the dynamically creation of the sub menus.

So it's necessary to focus the menu again to enable the mnemonics of the sub menus.

I also fixed the CommandBase and use the CommandManager.RequerySuggested on the CanExecuteChanged event, so it's not necessary to invalidate all the stuff per hand.

```
        public event EventHandler CanExecuteChanged
        {
            add => CommandManager.RequerySuggested += value;
            remove => CommandManager.RequerySuggested -= value;
        }
```

### CODE REVIEW

**Comment by RickStrahl** [comment]
That's awesome Jan! Thank you - I have to take a look and make sure that all still works, but if the Invalidate stuff works that's been something that has been bugging me for a long time.

Also need to think about moving to latest of MahApps, but last I checked there were quite a few breaking changes. When I get a little more free time.

**Comment by punker76** [comment]
I just tested the latest v1.6.4 and all works as expected. There should not a breaking change in there. The only one I would change is the window commands, so that it looks like the windows 10 ones. Is there a reason why the TitleBarHeight is 35 pixel?

**Comment by RickStrahl** [comment]
So I took a look at this and the refactor of the RequerySuggested definitely works and **it's a lot cleaner**.

Unfortunately though this fires the event continuously - including while editing in the editor. Every key typed in the editor triggers a command requery for example, and it has a noticable effect on the typing speed because it has to constantly context switch between the embedded browser COM objects and the WPF code that fires the menu requery.

Altogher there are probably a hundred commands or so that are hooked up to various things so even though the check code is tiny for each it adds up.

**Comment by punker76** [comment]
Can you give me some hints where I can show on which command can be slow down the typing? Cause I tested with more then one open documents and yes the CanExecute methods are called on every typing, but I can't see a performance issue.

**Comment by RickStrahl** [comment]
It's not super drastic but it's noticeable (at least to me since I check for this regularly). With original code  the cursor is smooth and instant. With the changes in the cursor has a very slight lag.

To check: What I do is compile with the old master code, then compile your branch. Copy the bin folder off somehwere so you can run both and compare.

**Comment by punker76** [comment]
I found a nasty performance issue with the Hunspell, which was fired every time I typed something

The fix up for the dictionary files was wrong (a typo)

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=AFF File not found: c:\Users\punker76\Documents\Git\MarkdownMonster\MarkdownMonster\bin\Debug\Editor\EN_US.aff
  Source=NHunspell
  StackTrace:
   at NHunspell.Hunspell.Load(String affFile, String dictFile, String key) in d:\Work\NHunspell\NHunspell\NHunspell\Hunspell.cs:line 384
```

2018-05-20_22h31_42

**Comment by RickStrahl** [comment]
Thanks Jan. Missed that in the last round of dictionary updates. There are a few additional things I just fixed up as well - the defaults all need to point at en-US not EN_US. 

FWIW, the the spellchecking code fires on a timer every 200ms or so if you are typing something so that too goes over the COM boundaries discussed earlier. Unfortunately that I can't stretch out much beyond the 200 ms, otherwise the spelled text gets out of sync with what's on the screen.

**Pull request merged**
