### PR TITLE
Add critical exception handler to LibGit2Sharp loading to fix Issue #497

### PR DESCRIPTION
**Pull request by gerardo-lijs**

### CODE REVIEW

**Comment by gerardo-lijs** [comment]
@RickStrahl  after it was able to load LibGit2Sharp it failed to find git.exe and again swallowed exception this time in the ExecuteGitCommand method in GetHelper which return result.HasError == false but result.ExitCode == -1. The whole class exception handling looks like a house of cards!

The root of the problem is that in this computer I was trying Markdown Monster, I only have GitHub Desktop Installed and git.exe is not in my PATH environment variable. There is a IsGitInstalled method in GitHelper which checks this but it's not being used in Markdown Monster.

Solution proposed number 1 will be to try Process.Start("git.exe") the first time you try to use Git command in the application and in case it fails explain to the user to install/repair git or add it to the path. This way, no methods will be used in GitHelper class and many not well handled exception avoided.

Solution number 2 is making Markdown Monster compatible with GitHub Desktop by trying to find it's installation via registry/folder and using that path instead of relying in PATH environment.

Let me know which solution do you think is better and if you want I can do a pull request for it.

**Comment by RickStrahl** [comment]
I think #2 would be preferrable. There is a `GitHelper.FindGitExecutable()` and I think we could just add the Github Desktop execution path there as the fallback position. 

Actually I wasn't aware that LibGit2Sharp required that Git is actually present which is why I didn't check originally. MM uses some Git operations natively (basically all that require authentication because LibGit2Sharp doesn't handle that very well)

As to the exception handling that's on purpose in this case. This is ancillary behavior and the last thing I want to have happen with Git operations is to crash the application due to an unhandled exception bubbling through to the top. There are only a handful of operations that are using the GitHelper and explicitly checking for errors after these 'external' operations seems reasonable to me in this use case.

**Comment by gerardo-lijs** [comment]
I agree solution #2 is the best. MM worked perfectly after installing Git for Windows. I will make it compatible with GitHub Desktop and do a pull request.

Regarding exceptions, if we make sure that we check git.exe file exists most of this shallowed exceptions will never happen. I guess it's something that doesn't really add much value right now. In contrast making it compatible with GitHub Desktop will help many users to Commit/Push directly from MM.

**Comment by gerardo-lijs** [comment]
@RickStrahl I'm still working on this. Exceptions and path discovery of git.exe with GitHub Desktop is done and works without any problems but I'm testing different options for a working solution for Git-Credentials.

Right now, MM works perfectly with Git for Windows only if git.exe is in the environment path variable. Maybe it's just enough to check for that and end this the practical way!

**Comment by RickStrahl** [comment]
If you can find a way to get git-credentials to work in a non-intrusive way that would be awesome, but maybe lets get that into a separate PR. For now, let's just get the file change in because that's a quick fix. I think adding git-credentials will require a whole bunch of additional changes to update various commands to use LibGit2Sharp instead of hte command line commands. 

I'll be happy to work with you on that if need be once there's a good way to handle the auth propagation from the credential store.

**Comment by gerardo-lijs** [comment]
Maybe LibGit2Sharp is the way to go and avoid command line tool at all. This small PR just adds some Exception Handling and I think it's safe to merge.

I will post the file changes to another branch/PR because I found that after running git.exe from another directory other exceptions arouse because of Environment.CurrentDirectory which should be change in my opinion to Assembly.GetEntryAssembly to avoid this possible errors. Will post that in another PR too.

I am glad to help and collaborate with you in MM. It's the first open source project I help with so please let me know if any part of the workflow could be done different/better.

PS: Congrats on your blog. Been following it for many years!

**Comment by RickStrahl** [comment]
So Environment.CurrentDirectory can be fixed with `App.InitialStartDirectory` which stays fixed at the initial startup path of the application (location of the exe always).

FWIW - I see your first initial commit with the placeholder code, but nothing else on this branch to date... 

As to making everything go through LibGit2Sharp as I said I would love to but there's gotta be a way to pick up the credentials, or else add full support for the oAuth flow to get Github token, which I'm not too keen on adding. Right now the command line commands pick up your current Git login or if not set prompt with the standard Git Credential Store dialog for various providers. The problem isn't so much the GitHub oAuth flow, but supporting Github, BitBucket, VS TS, GitLab etc. which becomes a massive chore to implement and maintain. Unless something has changed though I don't think LibGit2Sharp supports the Credential Manager and requires that you provide explicit tokens or auth.

Thanks for your help with this - the Git Integration was my first forray into working with a Git provider inside of an app, so I'm no expert and any help with this is appreciated.

**Comment by gerardo-lijs** [comment]
Correct, I found the App.InitialStartDirectory and fixed that. But I had the feeling I started going down the rabbit hole with every change I made and wanted to keep my PR focused. I did not push the code of using the git.exe from GitHub Desktop installation because it was not fully working (manual credentials needed).

I will push the not finished code to this fork in case you want to compare something. I'm testing right now direct credential manager solution with LibGit2Sharp, Git Credential Manager for Windows. I know it does not work directly, but I think the workaround suggested by Edward Thomson needs a second try. From all I was able to read it's what makes more sense to me. Even if it doesn't still great to test/learn Git integration in depth!

Will push more often not finished code to this branch. I'm putting about one hour a day into this research mixing it with work/family so the progress it's a little bit slow unfortunately! But we'll get there eventually...

**Comment by gerardo-lijs** [comment]
I managed to get the solution give by Edward to you in Stackoverflow working with some minor modifications. I paste here a sample code to push using git credentials. It works using the credentials already stored in the computer and prompts for credentials the first time with UI.

Only problem I'm having so far is when user is prompt for credentials and they enter an invalid user/password. Git writes to the console asking for user/pass and the process is not finished until you input that. Tried to monitor StandardError/Output with no success. I get the error text in stderror but only after filling that manually.

I will update MM fork in the nexts days to implement this!

```
public void PushLibGit2Sharp(string repositoryFolder, string branch)
{
    using (var repo = new Repository(repositoryFolder))
    {
        var options = new PushOptions
        {
            CredentialsProvider = (url, usernameFromUrl, types) =>
            {
                ProcessStartInfo startInfo = new ProcessStartInfo
                {
                    FileName = "git.exe",
                    Arguments = "credential fill",
                    UseShellExecute = false,
                    WindowStyle = ProcessWindowStyle.Hidden,
                    CreateNoWindow = true,
                    RedirectStandardInput = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true
                };

                Process process = new Process
                {
                    StartInfo = startInfo
                };

                process.Start();

                // Write query to stdin. 
                // For stdin to work we need to send \n instead of WriteLine
                // We need to send empty line at the end
                var uri = new Uri(url);
                process.StandardInput.NewLine = "\n";       
                process.StandardInput.WriteLine($"protocol={uri.Scheme}");
                process.StandardInput.WriteLine($"host={uri.Host}");
                process.StandardInput.WriteLine($"path={uri.AbsolutePath}");
                process.StandardInput.WriteLine();

                // Get user/pass from stdout
                string username = null;
                string password = null;
                string line;
                while ((line = process.StandardOutput.ReadLine()) != null)
                {
                    string[] details = line.Split('=');
                    if (details[0] == "username")
                    {
                        username = details[1];
                    }
                    else if (details[0] == "password")
                    {
                        password = details[1];
                    }
                }

                return new UsernamePasswordCredentials()
                {
                    Username = username,
                    Password = password
                };
            }
        };

        repo.Network.Push(repo.Branches[branch], options);
    }
}
```

**Comment by gerardo-lijs** [comment]
Just one final comment, even if the code in the previous comment/commit works using the git credential fill, it still relies in having Git for Windows installed in the system. It does not work using git.exe directly from GitHub Desktop (seems like credential-manager is not installed there). So I think we are back to square one and the only think that MM needs is to check that git.exe is correctly installed and that will do it with error messages/exceptions.

Still it was interesting to try all this alternatives and you can probably extract some code snippets from the commits, but if you want to Close this PR please go ahead!

**Pull request closed without merging**
