### PR TITLE
Support per-blog custom fields

### LINKED ISSUE #167: Support custom post metadata
A plugin I use on my blog requires that posts have a specific metadata ("custom field") set in wp_postmeta. When I create the post from the web UI, this metadata is inserted automatically, but not when I publish from MM. If I could specify custom fields to always set for this blog, it would be very helpful.

I realize it's a very specific use case, but without this change I can't publish directly from MM, or if I do, I have to add the metadata manually in the database, which is a pain... Anyway, the change is very small, as you'll see in the PR. The concept could also be extended to per-post custom fields.

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #167 

I didn't make any UI to set those, so for now it has to be done manually in WebLogAddIn.json.

### CODE REVIEW

**Comment by RickStrahl** [comment]
So this is something I'd been thinking about myself, but I think the implementation needs to be a little different.

I think it would be best to have an optional CustomFields dictionary on WeblogInfo, but in additional it would be nice to have a per post custom info that people can set in the meta data as well. This basically would allow for any extensions to be added 'manually' at least (and you could use a snippet to create a default template).

I'm not sure of your exact use case but I think this would still work with Weblog specific custom fields, so you could add them to WeblogInfo as you have, and that data is added to the post added MetaWeblogPostMetaData which also has a CustomFields dictionary.

**Comment by thomaslevesque** [comment]
Thanks for the merge!

> I think it would be best to have an optional CustomFields dictionary on WeblogInfo, but in additional it would be nice to have a per post custom info that people can set in the meta data as well. This basically would allow for any extensions to be added 'manually' at least (and you could use a snippet to create a default template).

Yes, per-post custom fields would definitely make sense!

**Comment by RickStrahl** [comment]
Adding now.

**Comment by RickStrahl** [comment]
So I've added support for custom fields in the post metadata. 

You can now do:

```xml
<customFields>
	<customField>
		<key>mt_test</key>
		<value>Some random value your server can handle</value>
	</customField>
	<customField>
		<key>mt_location</key>
		<value>Maui, Hawaii </value>
	</customField>
</customFields>
```

fa758d59b1238483345931ba234d1fd1e86e74ca

**Comment by thomaslevesque** [comment]
@RickStrahl nice!

**Comment by RickStrahl** [comment]
Curious: What are you setting at the Weblog level that needs to be sent with each post and presumably is static? Or are you adding stuff dynamically using an add-in or the scripting addin?

**Comment by thomaslevesque** [comment]
> Curious: What are you setting at the Weblog level that needs to be sent with each post and presumably is static? Or are you adding stuff dynamically using an add-in or the scripting addin?

It's specific to a Wordpress plugin I'm using ([Syntax Highlighter Evolved](https://wordpress.org/plugins/syntaxhighlighter/)). There's a custom field `_syntaxhighlighter_encoded` that needs to be set to '1' to prevent HTML encoding of characters in the code. Not sure why this is needed, but it's set automatically when I create the post via the web interface, and if it's not there, `<` and `>` appear as `&lt;` and `&gt;`.

**Comment by RickStrahl** [comment]
Can you do me a favor and also try this for post specific custom_fields just to check if that works on WordPress? I don't have a good test case to see if that goes all the way through for that (although I can see the custom fields getting sent).

* [Sending Custom Blog Fields](http://markdownmonster.west-wind.com/docs/_4v500dkm9.htm)

**Comment by thomaslevesque** [comment]
Sure, I'll give it a try

**Comment by thomaslevesque** [comment]
The fields are correctly inserted, for both weblog-level and post-level custom fields 👍 

However, I have good news and bad news:
- the bad news is that updating a blog post inserts duplicate entries in wp_postmeta (several entries with the same key for the same post). Since there's no unique constraint, WP doesn't seem to mind, but I don't know how it handles this case.
- the good news is that now I know what the `id` field is for: it's the database id of the post metadata. If it's specified, the existing metadata is updated. If it's not specified, a new row is inserted. Which explains #165... I tried it (by changing the values in the debugger), and if I set the ids with the values from the db, the custom fields are correctly updated.

This means that MM should:
- retrieve the custom fields from the published post and store the ids
- update the existing custom fields, if any, rather than add new ones

**Comment by RickStrahl** [comment]
Thanks for checking this out Thomas.

Ugh - that's ugly (and so unnecessary - they should just throw out the existing data and let it reload on an edit request 😠  ). Especially since now we're going to need to track the id along with the key and value. And that'd be tough for the Weblog Level ids.

**Comment by thomaslevesque** [comment]
> and so unnecessary - they should just throw out the existing data and let it reload on an edit request 😠

Well, maybe it's possible in some cases to have multiple instances of a given key... in this case it makes sense not to replace the existing data.

> And that'd be tough for the Weblog Level ids.

Ouch... didn't think of that.

**Comment by RickStrahl** [comment]
Maybe the thing to do is to create a List<CustomField> for the meta data, and import the WebLogInfo into it when the post is created and only add that data if it doesn't exist already. The post can then update the ID.

This gets to be a bit of a pain as dependencies need to be passed around but the concept should be good.

**Comment by thomaslevesque** [comment]
Sound good. I can give it a try if you want.

**Pull request merged**
