### PR TITLE
Fix custom fields

### LINKED ISSUE #165: Wordpress post meta (custom fields) are not added when publishing
The `mt_markdown` post meta is not inserted.

This seems to be because MM specifies both `id` and `key` for custom fields, but WordPress expects only `key`. Clearing `id` solves the problem. I'd send a PR, but I'm worried it could break things for non-WordPress blogs... Do you have a way to test it?

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #165

### CODE REVIEW

**Comment by thomaslevesque** [comment]
@RickStrahl did you close this PR intentionally? Is there something I should improve?

**Comment by RickStrahl** [comment]
Ooops - meant to merge not close :-)

**Comment by thomaslevesque** [comment]
Thanks for the merge! Now I think I can *really* use MM as my main editor for blogging :wink:

**Comment by RickStrahl** [comment]
:smile: sorry it took so long :-)

**Comment by thomaslevesque** [comment]
No problem! I was able to use MM already, I just had to make manual changes to the WordPress db ;)

**Pull request merged**
