### PR TITLE
Fix position of TabItem context menu

### PR DESCRIPTION
**Pull request by punker76**
@RickStrahl We saw this at summit and now I have a fix for it :-D

- Binding to the close command is also fixed
- MenuItem Background for context menu fixed

**Before**

image

image

**After**

image

image

**Background fix**

image

### CODE REVIEW

**Comment by RickStrahl** [comment]
Thanks Jan. 

When I run this the menu pops up to the left rather than the right. Any reason why that's different than what you have in your screen shots?

image

Any ideas?

**Comment by punker76** [comment]
@RickStrahl Hi Rick. Are you inside a virtual machine? Is this only happen to the context menu or also to the main menu?

**Comment by RickStrahl** [comment]
No virtual machine, running on the metal.

The main menu (correctly?) also points to the left. That's the way visual studio works so that is probably the way to should be. But tab menus in visual studio go right and while it might seem consistent to go left, it just doesn't feel right to have them open to the left. It works for the menus because the right align under the menu pads, but for the context menu there's nothing to line it up to.

**Comment by punker76** [comment]
@RickStrahl Can you just check this? Saw this problem now more than 2 times...
http://timsneath.com/windows-10-menu-alignment/
https://msdn.microsoft.com/en-us/library/system.windows.systemparameters.menudropalignment.aspx

**Comment by RickStrahl** [comment]
I don't  those Tablet options, most likely because I don't have a touch screen.

The second - I'll check later, but I'm pretty sure it's the alignment is right (ie. opens to left) as all menus are opening to the left. However as mentioned in Visual Studio, tab menus goes the other way.

On your system how is that set up? Your menus open left aligned?

**Pull request merged**
