### PR TITLE
Update README.md to include Scoop installer

### PR DESCRIPTION
**Pull request by sytone**
Add instructions to install and update using Scoop as another alternative to direct installation and chocolatey.

### CODE REVIEW

**Comment by RickStrahl** [comment]
I need to review this to see what the package is doing. I can't find any info on Package management or package information. None of the documentation that I can find they have talk about package creation.

**Comment by sytone** [comment]
Manifest information can be found here: https://github.com/lukesampson/scoop/wiki/App-Manifests 

The manifest for MarkdownMonster can be found here: https://github.com/lukesampson/scoop-extras/blob/master/bucket/markdown-monster.json

**Comment by RickStrahl** [comment]
Made adjustments to the Scoop manifest to install full version. Not very happy about the fact they are forcing a semi-portable install, but at least now it's running the full installer.

**Comment by sytone** [comment]
The goal o scoop is no admin based install. Having the settings in a symlink helps to backup so have appreciated that. Scoop is more dev focused rather than end user focused.

**Pull request merged**
