### PR TITLE
Fix missing TextBox inheritence

### PR DESCRIPTION
**Pull request by punker76**
You need to inherit from the base/original MahApps style. You can do this

with

```
<Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource MetroTextBox}">
...
</Style>
```

or

```
<Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource {x:Type TextBox}}">
...
</Style>
```

### CODE REVIEW

**Comment by RickStrahl** [comment]
Hmmm... so this fixes the styling but it also removes the spell checking words from the context menu.

image

**Comment by punker76** [comment]
@RickStrahl Saw this too on testing, currently investigating what's wrong here.

**Comment by punker76** [comment]
@RickStrahl ah :-) it's a change after 1.5.0 and is already fixed in 1.6.0 alpha. Workaround for now is to use `TextBoxHelper.IsSpellCheckContextMenuEnabled="True"`.

**Comment by punker76** [comment]
@RickStrahl https://github.com/RickStrahl/MarkdownMonster/pull/244

**Pull request merged**
